apiVersion: v1
kind: Service
metadata:
  name: {{ include "users-db-chart.fullname" . }}
#  name: postgres
  labels:
    {{- include "users-db-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "users-db-chart.selectorLabels" . | nindent 4 }}
